{{- if .Values.mockDefinitions.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mockd.fullname" . }}-mocks
  labels:
    {{- include "mockd.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.mockDefinitions.mocks }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}
{{- end }}
