apiVersion: v2
name: mockd
description: A Helm chart for deploying mockd - a powerful HTTP mocking server
type: application
version: 0.2.3
appVersion: "0.2.3"
keywords:
  - mock
  - http
  - api
  - testing
  - mocking
home: https://github.com/getmockd/mockd
sources:
  - https://github.com/getmockd/mockd
maintainers:
  - name: mockd
    url: https://github.com/getmockd
